In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('flight.csv')

In [ ]:
df.head()

,flight_id,airline,source_city,destination_city,departure_time,stops,duration_hours,days_left,price
0,1,Indigo,Delhi,Mumbai,Morning,non-stop,2.5,15,5200
1,2,AirIndia,Mumbai,Bangalore,Evening,1-stop,5.0,10,6400
2,3,SpiceJet,Delhi,Chennai,Afternoon,1-stop,4.5,7,5900
3,4,Vistara,Kolkata,Delhi,Morning,non-stop,2.0,20,4500
4,5,Indigo,Bangalore,Mumbai,Night,2+-stop,7.5,5,7200

In [14]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/bhoomikami2710-sys/Bhoomika_ML/refs/heads/main/csv/spotify.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [21]:
pd.read_csv('student.tsv',sep='\t')

    StudentID  CGPA  Internships  Projects  Package_LPA
0         101   8.1            2         3          6.5
1         102   7.5            1         2          5.2
2         103   9.0            3         4          9.1
3         104   6.8            0         2          4.0
4         105   8.7            2         5          8.3
5         106   7.9            1         3          6.0
6         107   9.3            4         6         10.5
7         108   6.5            0         1          3.8
8         109   8.4            2         4          7.2
9         110   7.2            1         2          5.0
10        111   8.9            3         5          8.9
11        112   6.9            1         2          4.5
12        113   9.5            4         6         11.2
13        114   7.8            2         3          6.3
14        115   8.2            2         4          7.5
15        116   7.4            1         2          5.6
16        117   8.6            3         5          8.1
17        118   6.7            0         1          4.2
18        119   9.1            3         5          9.8
19        120   7.3            1         2          5.4

In [25]:
pd.read_csv('student.tsv', sep='\t', index_col='StudentID')

           CGPA  Internships  Projects  Package_LPA
StudentID
101         8.1            2         3          6.5
102         7.5            1         2          5.2
103         9.0            3         4          9.1
104         6.8            0         2          4.0
105         8.7            2         5          8.3
106         7.9            1         3          6.0
107         9.3            4         6         10.5
108         6.5            0         1          3.8
109         8.4            2         4          7.2
110         7.2            1         2          5.0
111         8.9            3         5          8.9
112         6.9            1         2          4.5
113         9.5            4         6         11.2
114         7.8            2         3          6.3
115         8.2            2         4          7.5
116         7.4            1         2          5.6
117         8.6            3         5          8.1
118         6.7            0         1          4.2
119         9.1            3         5          9.8
120         7.3            1         2          5.4

In [28]:
df = pd.read_csv('flight.csv',header=4)
df

     4   Vistara    Kolkata      Delhi    Morning  non-stop  2.0  20  4500
0    5    Indigo  Bangalore     Mumbai      Night   2+-stop  7.5   5  7200
1    6   AirAsia      Delhi    Kolkata  Afternoon  non-stop  2.2  18  4100
2    7     GoAir     Mumbai    Chennai    Evening    1-stop  4.0  12  5600
3    8   Vistara    Chennai      Delhi    Morning  non-stop  2.8  25  4800
4    9  SpiceJet  Bangalore    Kolkata      Night    1-stop  5.5   9  6100
5   10    Indigo      Delhi  Bangalore  Afternoon  non-stop  2.6  30  5300
6   11  AirIndia    Kolkata     Mumbai    Morning    1-stop  4.8   6  6700
7   12     GoAir    Chennai  Bangalore    Evening  non-stop  1.5  22  3900
8   13   AirAsia     Mumbai      Delhi      Night  non-stop  2.4  14  5000
9   14   Vistara  Bangalore    Chennai  Afternoon  non-stop  1.2  19  3600
10  15  SpiceJet      Delhi    Kolkata    Evening    1-stop  3.5   8  5800
11  16    Indigo     Mumbai    Chennai    Morning  non-stop  2.1  27  4700
12  17  AirIndia      Delhi  Bangalore      Night   2+-stop  8.0   4  7500
13  18     GoAir    Kolkata    Chennai  Afternoon    1-stop  4.2  11  6200
14  19   AirAsia  Bangalore      Delhi    Evening  non-stop  2.7  16  5100
15  20   Vistara     Mumbai    Kolkata    Morning  non-stop  2.3  21  4900
16  21  SpiceJet    Chennai     Mumbai      Night    1-stop  5.1  13  6000
17  22    Indigo    Kolkata  Bangalore  Afternoon  non-stop  2.9  17  5200
18  23  AirIndia      Delhi    Chennai    Morning    1-stop  4.6   6  6900
19  24     GoAir     Mumbai      Delhi    Evening  non-stop  2.5  24  5300
20  25   AirAsia    Chennai    Kolkata      Night    1-stop  5.3  10  6100
21  26   Vistara  Bangalore     Mumbai    Morning  non-stop  1.8  26  4400
22  27  SpiceJet      Delhi     Mumbai  Afternoon  non-stop  2.4  29  5000
23  28    Indigo    Kolkata      Delhi    Evening  non-stop  2.2  23  4600
24  29  AirIndia     Mumbai  Bangalore      Night    1-stop  4.9   7  6800
25  30     GoAir      Delhi    Chennai    Morning    1-stop  4.4  12  5700

In [30]:
pd.read_csv('student.tsv', sep='\t', usecols=['StudentID','CGPA','Package_LPA'])

    StudentID  CGPA  Package_LPA
0         101   8.1          6.5
1         102   7.5          5.2
2         103   9.0          9.1
3         104   6.8          4.0
4         105   8.7          8.3
5         106   7.9          6.0
6         107   9.3         10.5
7         108   6.5          3.8
8         109   8.4          7.2
9         110   7.2          5.0
10        111   8.9          8.9
11        112   6.9          4.5
12        113   9.5         11.2
13        114   7.8          6.3
14        115   8.2          7.5
15        116   7.4          5.6
16        117   8.6          8.1
17        118   6.7          4.2
18        119   9.1          9.8
19        120   7.3          5.4

In [32]:
pd.read_csv('flight.csv',usecols=['airline'])

     airline
0     Indigo
1   AirIndia
2   SpiceJet
3    Vistara
4     Indigo
5    AirAsia
6      GoAir
7    Vistara
8   SpiceJet
9     Indigo
10  AirIndia
11     GoAir
12   AirAsia
13   Vistara
14  SpiceJet
15    Indigo
16  AirIndia
17     GoAir
18   AirAsia
19   Vistara
20  SpiceJet
21    Indigo
22  AirIndia
23     GoAir
24   AirAsia
25   Vistara
26  SpiceJet
27    Indigo
28  AirIndia
29     GoAir

In [34]:
pd.read_csv('spotify.csv',skiprows=[1,2])

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.210,0.000000,0.1170,0.1200,76.332,4,acoustic
1,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.905,0.000071,0.1320,0.1430,181.740,3,acoustic
2,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.469,0.000000,0.0829,0.1670,119.949,4,acoustic
3,5,5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,...,-8.807,1,0.1050,0.289,0.000000,0.1890,0.6660,98.017,4,acoustic
4,6,6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,...,-8.822,1,0.0355,0.857,0.000003,0.0913,0.0765,141.284,3,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113993,113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,...,-16.393,1,0.0422,0.640,0.928000,0.0863,0.0339,125.995,5,world-music
113994,113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,...,-18.318,0,0.0401,0.994,0.976000,0.1050,0.0350,85.239,4,world-music
113995,113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,...,-10.895,0,0.0420,0.867,0.000000,0.0839,0.7430,132.378,4,world-music
113996,113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,...,-10.889,1,0.0297,0.381,0.000000,0.2700,0.4130,135.960,4,world-music
113997,113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,...,-10.204,0,0.0725,0.681,0.000000,0.0893,0.7080,79.198,4,world-music

In [41]:
pd.read_csv('Player.csv', sep=':', on_bad_lines='skip')

    Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,
0    1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medi...
1    2,BB McCullum,27-Sep-81,Right_Hand,Right-arm m...
2    3,RT Ponting,19-Dec-74,Right_Hand,Right-arm me...
3    4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm off...
4    5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-a...
..                                                 ...
518            519,Subroto Das,NULL,NULL,NULL,India,1,
519           520,K Srinivasan,NULL,NULL,NULL,India,1,
520              521,VK Sharma,NULL,NULL,NULL,India,1,
521  523,AV Wankhade,14-Mar-92,Right_Hand,NULL,Indi...
522  524,B Aparajith,8-Jul-94,Right_Hand,Right-arm ...

[523 rows x 1 columns]

In [43]:
pd.read_csv('spotify.csv',dtype={'mode':float})

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0.0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1.0,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1.0,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1.0,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1.0,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,...,-16.393,1.0,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,...,-18.318,0.0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,...,-10.895,0.0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,...,-10.889,1.0,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,...,-10.204,0.0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [47]:
pd.read_csv('flight.csv')

,flight_id,airline,source_city,destination_city,departure_time,stops,duration_hours,days_left,price
0,1,Indigo,Delhi,Mumbai,Morning,non-stop,2.5,15,5200
1,2,AirIndia,Mumbai,Bangalore,Evening,1-stop,5.0,10,6400
2,3,SpiceJet,Delhi,Chennai,Afternoon,1-stop,4.5,7,5900
3,4,Vistara,Kolkata,Delhi,Morning,non-stop,2.0,20,4500
4,5,Indigo,Bangalore,Mumbai,Night,2+-stop,7.5,5,7200
5,6,AirAsia,Delhi,Kolkata,Afternoon,non-stop,2.2,18,4100
6,7,GoAir,Mumbai,Chennai,Evening,1-stop,4.0,12,5600
7,8,Vistara,Chennai,Delhi,Morning,non-stop,2.8,25,4800
8,9,SpiceJet,Bangalore,Kolkata,Night,1-stop,5.5,9,6100
9,10,Indigo,Delhi,Bangalore,Afternoon,non-stop,2.6,30,5300
10,11,AirIndia,Kolkata,Mumbai,Morning,1-stop,4.8,6,6700
11,12,GoAir,Chennai,Bangalore,Evening,non-stop,1.5,22,3900
12,13,AirAsia,Mumbai,Delhi,Night,non-stop,2.4,14,5000
13,14,Vistara,Bangalore,Chennai,Afternoon,non-stop,1.2,19,3600
14,15,SpiceJet,Delhi,Kolkata,Evening,1-stop,3.5,8,5800
15,16,Indigo,Mumbai,Chennai,Morning,non-stop,2.1,27,4700
16,17,AirIndia,Delhi,Bangalore,Night,2+-stop,8.0,4,7500
17,18,GoAir,Kolkata,Chennai,Afternoon,1-stop,4.2,11,6200
18,19,AirAsia,Bangalore,Delhi,Evening,non-stop,2.7,16,5100
19,20,Vistara,Mumbai,Kolkata,Morning,non-stop,2.3,21,4900
20,21,SpiceJet,Chennai,Mumbai,Night,1-stop,5.1,13,6000
21,22,Indigo,Kolkata,Bangalore,Afternoon,non-stop,2.9,17,5200
22,23,AirIndia,Delhi,Chennai,Morning,1-stop,4.6,6,6900
23,24,GoAir,Mumbai,Delhi,Evening,non-stop,2.5,24,5300
24,25,AirAsia,Chennai,Kolkata,Night,1-stop,5.3,10,6100
25,26,Vistara,Bangalore,Mumbai,Morning,non-stop,1.8,26,4400
26,27,SpiceJet,Delhi,Mumbai,Afternoon,non-stop,2.4,29,5000
27,28,Indigo,Kolkata,Delhi,Evening,non-stop,2.2,23,4600
28,29,AirIndia,Mumbai,Bangalore,Night,1-stop,4.9,7,6800
29,30,GoAir,Delhi,Chennai,Morning,1-stop,4.4,12,5700

In [48]:
def rename(name):
    if name == "AirIndia":
        return "AI"
    else:
        return name

In [49]:
rename("AirIndia")

'AI'

In [50]:
pd.read_csv('flight.csv',converters={'airline':rename})

,flight_id,airline,source_city,destination_city,departure_time,stops,duration_hours,days_left,price
0,1,Indigo,Delhi,Mumbai,Morning,non-stop,2.5,15,5200
1,2,AI,Mumbai,Bangalore,Evening,1-stop,5.0,10,6400
2,3,SpiceJet,Delhi,Chennai,Afternoon,1-stop,4.5,7,5900
3,4,Vistara,Kolkata,Delhi,Morning,non-stop,2.0,20,4500
4,5,Indigo,Bangalore,Mumbai,Night,2+-stop,7.5,5,7200
5,6,AirAsia,Delhi,Kolkata,Afternoon,non-stop,2.2,18,4100
6,7,GoAir,Mumbai,Chennai,Evening,1-stop,4.0,12,5600
7,8,Vistara,Chennai,Delhi,Morning,non-stop,2.8,25,4800
8,9,SpiceJet,Bangalore,Kolkata,Night,1-stop,5.5,9,6100
9,10,Indigo,Delhi,Bangalore,Afternoon,non-stop,2.6,30,5300
10,11,AI,Kolkata,Mumbai,Morning,1-stop,4.8,6,6700
11,12,GoAir,Chennai,Bangalore,Evening,non-stop,1.5,22,3900
12,13,AirAsia,Mumbai,Delhi,Night,non-stop,2.4,14,5000
13,14,Vistara,Bangalore,Chennai,Afternoon,non-stop,1.2,19,3600
14,15,SpiceJet,Delhi,Kolkata,Evening,1-stop,3.5,8,5800
15,16,Indigo,Mumbai,Chennai,Morning,non-stop,2.1,27,4700
16,17,AI,Delhi,Bangalore,Night,2+-stop,8.0,4,7500
17,18,GoAir,Kolkata,Chennai,Afternoon,1-stop,4.2,11,6200
18,19,AirAsia,Bangalore,Delhi,Evening,non-stop,2.7,16,5100
19,20,Vistara,Mumbai,Kolkata,Morning,non-stop,2.3,21,4900
20,21,SpiceJet,Chennai,Mumbai,Night,1-stop,5.1,13,6000
21,22,Indigo,Kolkata,Bangalore,Afternoon,non-stop,2.9,17,5200
22,23,AI,Delhi,Chennai,Morning,1-stop,4.6,6,6900
23,24,GoAir,Mumbai,Delhi,Evening,non-stop,2.5,24,5300
24,25,AirAsia,Chennai,Kolkata,Night,1-stop,5.3,10,6100
25,26,Vistara,Bangalore,Mumbai,Morning,non-stop,1.8,26,4400
26,27,SpiceJet,Delhi,Mumbai,Afternoon,non-stop,2.4,29,5000
27,28,Indigo,Kolkata,Delhi,Evening,non-stop,2.2,23,4600
28,29,AI,Mumbai,Bangalore,Night,1-stop,4.9,7,6800
29,30,GoAir,Delhi,Chennai,Morning,1-stop,4.4,12,5700

In [51]:
pd.read_csv('flight.csv',na_values=['Mumbai',])

,flight_id,airline,source_city,destination_city,departure_time,stops,duration_hours,days_left,price
0,1,Indigo,Delhi,NaN,Morning,non-stop,2.5,15,5200
1,2,AirIndia,NaN,Bangalore,Evening,1-stop,5.0,10,6400
2,3,SpiceJet,Delhi,Chennai,Afternoon,1-stop,4.5,7,5900
3,4,Vistara,Kolkata,Delhi,Morning,non-stop,2.0,20,4500
4,5,Indigo,Bangalore,NaN,Night,2+-stop,7.5,5,7200
5,6,AirAsia,Delhi,Kolkata,Afternoon,non-stop,2.2,18,4100
6,7,GoAir,NaN,Chennai,Evening,1-stop,4.0,12,5600
7,8,Vistara,Chennai,Delhi,Morning,non-stop,2.8,25,4800
8,9,SpiceJet,Bangalore,Kolkata,Night,1-stop,5.5,9,6100
9,10,Indigo,Delhi,Bangalore,Afternoon,non-stop,2.6,30,5300
10,11,AirIndia,Kolkata,NaN,Morning,1-stop,4.8,6,6700
11,12,GoAir,Chennai,Bangalore,Evening,non-stop,1.5,22,3900
12,13,AirAsia,NaN,Delhi,Night,non-stop,2.4,14,5000
13,14,Vistara,Bangalore,Chennai,Afternoon,non-stop,1.2,19,3600
14,15,SpiceJet,Delhi,Kolkata,Evening,1-stop,3.5,8,5800
15,16,Indigo,NaN,Chennai,Morning,non-stop,2.1,27,4700
16,17,AirIndia,Delhi,Bangalore,Night,2+-stop,8.0,4,7500
17,18,GoAir,Kolkata,Chennai,Afternoon,1-stop,4.2,11,6200
18,19,AirAsia,Bangalore,Delhi,Evening,non-stop,2.7,16,5100
19,20,Vistara,NaN,Kolkata,Morning,non-stop,2.3,21,4900
20,21,SpiceJet,Chennai,NaN,Night,1-stop,5.1,13,6000
21,22,Indigo,Kolkata,Bangalore,Afternoon,non-stop,2.9,17,5200
22,23,AirIndia,Delhi,Chennai,Morning,1-stop,4.6,6,6900
23,24,GoAir,NaN,Delhi,Evening,non-stop,2.5,24,5300
24,25,AirAsia,Chennai,Kolkata,Night,1-stop,5.3,10,6100
25,26,Vistara,Bangalore,NaN,Morning,non-stop,1.8,26,4400
26,27,SpiceJet,Delhi,NaN,Afternoon,non-stop,2.4,29,5000
27,28,Indigo,Kolkata,Delhi,Evening,non-stop,2.2,23,4600
28,29,AirIndia,NaN,Bangalore,Night,1-stop,4.9,7,6800
29,30,GoAir,Delhi,Chennai,Morning,1-stop,4.4,12,5700

In [53]:
dfs = pd.read_csv('flight.csv',chunksize=450)

In [55]:
for chunks in dfs:
    print(chunks.shape)