In [24]:
class BLR:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train,y_train):

        num = 0
        den = 0

        for i in range(X_train.shape[0]):

            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,X_test):

        return self.m * X_test + self.b

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('jee.csv')

In [7]:
df.head()

   12th_Marks  JEE_Percentile
0          96           88.04
1         100           58.54
2          62           91.12
3          74           66.92
4          62           60.68

In [10]:
X = df.iloc[:,0:1]
Y = df.iloc[:,-1]

In [11]:
X

    12th_Marks
0           96
1          100
2           62
3           74
4           62
..         ...
95          66
96          75
97          94
98          61
99          71

[100 rows x 1 columns]

In [12]:
Y

0     88.04
1     58.54
2     91.12
3     66.92
4     60.68
      ...
95    59.13
96    77.91
97    86.03
98    52.39
99    93.98
Name: JEE_Percentile, Length: 100, dtype: float64

In [14]:
df.shape

(100, 2)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [21]:
X_train.shape

(80, 1)

In [22]:
Y_train.shape

(80,)

In [25]:
lr = BLR()

In [29]:
lr.fit(X_train.values, Y_train.values)
X_test_value = X_test.iloc[0, 0]
print(lr.predict(X_test_value))

[0.15997021]
[62.13051435]
[72.36860793]